# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j3y17lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j3y17lte/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/j3y17lte/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh \
    vendor/samsung/j3y17lte/proprietary/etc/ca.pem:system/etc/ca.pem \
    vendor/samsung/j3y17lte/proprietary/etc/plmn_delta.bin:system/etc/plmn_delta.bin \
    vendor/samsung/j3y17lte/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    vendor/samsung/j3y17lte/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/j3y17lte/proprietary/etc/wifi/mx140.bin:system/etc/wifi/mx140.bin \
    vendor/samsung/j3y17lte/proprietary/etc/wifi/mx140_t.bin:system/etc/wifi/mx140_t.bin \
    vendor/samsung/j3y17lte/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/samsung/j3y17lte/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/j3y17lte/proprietary/lib/hw/camera.universal7570.so:system/lib/hw/camera.universal7570.so \
    vendor/samsung/j3y17lte/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/j3y17lte/proprietary/lib/hw/sensors.universal7570.so:system/lib/hw/sensors.universal7570.so \
    vendor/samsung/j3y17lte/proprietary/lib/libHpr_RecFace_dl_v1.0.so:system/lib/libHpr_RecFace_dl_v1.0.so \
    vendor/samsung/j3y17lte/proprietary/lib/libHpr_RecGAE_cvFeature_v1.0.so:system/lib/libHpr_RecGAE_cvFeature_v1.0.so \
    vendor/samsung/j3y17lte/proprietary/lib/libHpr_TaskFaceClustering_hierarchical_v1.0.so:system/lib/libHpr_TaskFaceClustering_hierarchical_v1.0.so \
    vendor/samsung/j3y17lte/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/j3y17lte/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/j3y17lte/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
    vendor/samsung/j3y17lte/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/j3y17lte/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/j3y17lte/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
    vendor/samsung/j3y17lte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/j3y17lte/proprietary/lib/libseccameracore.so:system/lib/libseccameracore.so \
    vendor/samsung/j3y17lte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/j3y17lte/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/j3y17lte/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/j3y17lte/proprietary/lib/libsensorservice.so:system/lib/libsensorservice.so \
    vendor/samsung/j3y17lte/proprietary/lib/libstainkiller.so:system/lib/libstainkiller.so \
    vendor/samsung/j3y17lte/proprietary/lib/libuniplugin.so:system/lib/libuniplugin.so \
    vendor/samsung/j3y17lte/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/j3y17lte/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/j3y17lte/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/j3y17lte/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/j3y17lte/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/j3y17lte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/j3y17lte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/j3y17lte/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/j3y17lte/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/j3y17lte/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/j3y17lte/proprietary/vendor/firmware/bcm43438A1_V0068.0286.hcd:system/vendor/firmware/bcm43438A1_V0068.0286.hcd \
    vendor/samsung/j3y17lte/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/j3y17lte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/j3y17lte/proprietary/vendor/firmware/setfile_4h5yc.bin:system/vendor/firmware/setfile_4h5yc.bin \
    vendor/samsung/j3y17lte/proprietary/vendor/firmware/setfile_imx258.bin:system/vendor/firmware/setfile_imx258.bin \
    vendor/samsung/j3y17lte/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/j3y17lte/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/samsung/j3y17lte/proprietary/vendor/lib/libHpr_LocFace_mvfd_v1.0.so:system/vendor/lib/libHpr_LocFace_mvfd_v1.0.so \
    vendor/samsung/j3y17lte/proprietary/vendor/lib/libHpr_LocLandmark_sdm_v1.0.so:system/vendor/lib/libHpr_LocLandmark_sdm_v1.0.so \
    vendor/samsung/j3y17lte/proprietary/vendor/lib/libSEF.so:system/vendor/lib/libSEF.so \
    vendor/samsung/j3y17lte/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/j3y17lte/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
    
# Create Mali links for Vulkan and OpenCL
PRODUCT_PACKAGES += libGLES_mali

##BSP
PRODUCT_COPY_FILES += \
    vendor/samsung/j3y17lte/proprietary/lib/hw/gatekeeper.exynos7570.so:system/lib/hw/gatekeeper.exynos7570.so \
    vendor/samsung/j3y17lte/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/j3y17lte/proprietary/lib/hw/hwcomposer.exynos5.so:system/lib/hw/hwcomposer.exynos5.so \
    vendor/samsung/j3y17lte/proprietary/lib/hw/keystore.exynos7570.so:system/lib/hw/keystore.exynos7570.so \
    vendor/samsung/j3y17lte/proprietary/lib/hw/memtrack.exynos5.so:system/lib/hw/memtrack.exynos5.so \
    vendor/samsung/j3y17lte/proprietary/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/samsung/j3y17lte/proprietary/lib/libhwcutils.so:system/lib/libhwcutils.so \
    vendor/samsung/j3y17lte/proprietary/lib/libmpp.so:system/lib/libmpp.so \
    vendor/samsung/j3y17lte/proprietary/lib/libcsc.so:system/lib/libcsc.so \
    vendor/samsung/j3y17lte/proprietary/lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
    vendor/samsung/j3y17lte/proprietary/lib/libexynosscaler.so:system/lib/libexynosscaler.so \
    vendor/samsung/j3y17lte/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
    vendor/samsung/j3y17lte/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/j3y17lte/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so
    
## OMX old BSP
PRODUCT_COPY_FILES += \
    vendor/samsung/j3y17lte/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
    vendor/samsung/j3y17lte/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
    vendor/samsung/j3y17lte/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so
